# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fizzy_ocr.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x66izzy_ocr.proto\x12\x08\x66izzyocr\"\x9d\x01\n\x07Polygon\x12!\n\x08left_top\x18\x01 \x01(\x0b\x32\x0f.fizzyocr.Coord\x12\"\n\tright_top\x18\x02 \x01(\x0b\x32\x0f.fizzyocr.Coord\x12%\n\x0cright_bottom\x18\x03 \x01(\x0b\x32\x0f.fizzyocr.Coord\x12$\n\x0bleft_bottom\x18\x04 \x01(\x0b\x32\x0f.fizzyocr.Coord\"\x1d\n\x05\x43oord\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\"F\n\rGeneralOCRReq\x12\x11\n\timage_url\x18\x01 \x01(\t\x12\x14\n\x0cimage_base64\x18\x02 \x01(\t\x12\x0c\n\x04lang\x18\x03 \x01(\t\"x\n\x12GeneralPrintOCRRsp\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x13\n\x0b\x63onsum_time\x18\x03 \x01(\x03\x12.\n\x04\x64\x61ta\x18\x04 \x01(\x0b\x32 .fizzyocr.GeneralPrintOCRRspData\"L\n\x16GeneralPrintOCRRspData\x12\x32\n\x04item\x18\x01 \x03(\x0b\x32$.fizzyocr.GeneralPrintOCRRspDataItem\"`\n\x1aGeneralPrintOCRRspDataItem\x12\"\n\x07polygon\x18\x01 \x01(\x0b\x32\x11.fizzyocr.Polygon\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\r\n\x05score\x18\x03 \x01(\x02\x42\rZ\x0b./;fizzyocrb\x06proto3')



_POLYGON = DESCRIPTOR.message_types_by_name['Polygon']
_COORD = DESCRIPTOR.message_types_by_name['Coord']
_GENERALOCRREQ = DESCRIPTOR.message_types_by_name['GeneralOCRReq']
_GENERALPRINTOCRRSP = DESCRIPTOR.message_types_by_name['GeneralPrintOCRRsp']
_GENERALPRINTOCRRSPDATA = DESCRIPTOR.message_types_by_name['GeneralPrintOCRRspData']
_GENERALPRINTOCRRSPDATAITEM = DESCRIPTOR.message_types_by_name['GeneralPrintOCRRspDataItem']
Polygon = _reflection.GeneratedProtocolMessageType('Polygon', (_message.Message,), {
  'DESCRIPTOR' : _POLYGON,
  '__module__' : 'fizzy_ocr_pb2'
  # @@protoc_insertion_point(class_scope:fizzyocr.Polygon)
  })
_sym_db.RegisterMessage(Polygon)

Coord = _reflection.GeneratedProtocolMessageType('Coord', (_message.Message,), {
  'DESCRIPTOR' : _COORD,
  '__module__' : 'fizzy_ocr_pb2'
  # @@protoc_insertion_point(class_scope:fizzyocr.Coord)
  })
_sym_db.RegisterMessage(Coord)

GeneralOCRReq = _reflection.GeneratedProtocolMessageType('GeneralOCRReq', (_message.Message,), {
  'DESCRIPTOR' : _GENERALOCRREQ,
  '__module__' : 'fizzy_ocr_pb2'
  # @@protoc_insertion_point(class_scope:fizzyocr.GeneralOCRReq)
  })
_sym_db.RegisterMessage(GeneralOCRReq)

GeneralPrintOCRRsp = _reflection.GeneratedProtocolMessageType('GeneralPrintOCRRsp', (_message.Message,), {
  'DESCRIPTOR' : _GENERALPRINTOCRRSP,
  '__module__' : 'fizzy_ocr_pb2'
  # @@protoc_insertion_point(class_scope:fizzyocr.GeneralPrintOCRRsp)
  })
_sym_db.RegisterMessage(GeneralPrintOCRRsp)

GeneralPrintOCRRspData = _reflection.GeneratedProtocolMessageType('GeneralPrintOCRRspData', (_message.Message,), {
  'DESCRIPTOR' : _GENERALPRINTOCRRSPDATA,
  '__module__' : 'fizzy_ocr_pb2'
  # @@protoc_insertion_point(class_scope:fizzyocr.GeneralPrintOCRRspData)
  })
_sym_db.RegisterMessage(GeneralPrintOCRRspData)

GeneralPrintOCRRspDataItem = _reflection.GeneratedProtocolMessageType('GeneralPrintOCRRspDataItem', (_message.Message,), {
  'DESCRIPTOR' : _GENERALPRINTOCRRSPDATAITEM,
  '__module__' : 'fizzy_ocr_pb2'
  # @@protoc_insertion_point(class_scope:fizzyocr.GeneralPrintOCRRspDataItem)
  })
_sym_db.RegisterMessage(GeneralPrintOCRRspDataItem)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\013./;fizzyocr'
  _POLYGON._serialized_start=30
  _POLYGON._serialized_end=187
  _COORD._serialized_start=189
  _COORD._serialized_end=218
  _GENERALOCRREQ._serialized_start=220
  _GENERALOCRREQ._serialized_end=290
  _GENERALPRINTOCRRSP._serialized_start=292
  _GENERALPRINTOCRRSP._serialized_end=412
  _GENERALPRINTOCRRSPDATA._serialized_start=414
  _GENERALPRINTOCRRSPDATA._serialized_end=490
  _GENERALPRINTOCRRSPDATAITEM._serialized_start=492
  _GENERALPRINTOCRRSPDATAITEM._serialized_end=588
# @@protoc_insertion_point(module_scope)
