# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import fizzy_ocr_pb2 as fizzy__ocr__pb2


class FizzyOcrPaddleStub(object):
    """票据OCR接口在此定义
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GeneralPrintOCRV1 = channel.unary_unary(
                '/fizzyocr.FizzyOcrPaddle/GeneralPrintOCRV1',
                request_serializer=fizzy__ocr__pb2.GeneralOCRReq.SerializeToString,
                response_deserializer=fizzy__ocr__pb2.GeneralPrintOCRRsp.FromString,
                )


class FizzyOcrPaddleServicer(object):
    """票据OCR接口在此定义
    """

    def GeneralPrintOCRV1(self, request, context):
        """通用印刷体识别V1
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FizzyOcrPaddleServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GeneralPrintOCRV1': grpc.unary_unary_rpc_method_handler(
                    servicer.GeneralPrintOCRV1,
                    request_deserializer=fizzy__ocr__pb2.GeneralOCRReq.FromString,
                    response_serializer=fizzy__ocr__pb2.GeneralPrintOCRRsp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fizzyocr.FizzyOcrPaddle', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FizzyOcrPaddle(object):
    """票据OCR接口在此定义
    """

    @staticmethod
    def GeneralPrintOCRV1(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fizzyocr.FizzyOcrPaddle/GeneralPrintOCRV1',
            fizzy__ocr__pb2.GeneralOCRReq.SerializeToString,
            fizzy__ocr__pb2.GeneralPrintOCRRsp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
