# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fizzy_ocr_paddle.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import service as _service
from google.protobuf import service_reflection
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import fizzy_ocr_pb2 as fizzy__ocr__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x66izzy_ocr_paddle.proto\x12\x08\x66izzyocr\x1a\x0f\x66izzy_ocr.proto2^\n\x0e\x46izzyOcrPaddle\x12L\n\x11GeneralPrintOCRV1\x12\x17.fizzyocr.GeneralOCRReq\x1a\x1c.fizzyocr.GeneralPrintOCRRsp\"\x00\x42\x10Z\x0b./;fizzyocr\x90\x01\x01\x62\x06proto3')



_FIZZYOCRPADDLE = DESCRIPTOR.services_by_name['FizzyOcrPaddle']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\013./;fizzyocr\220\001\001'
  _FIZZYOCRPADDLE._serialized_start=53
  _FIZZYOCRPADDLE._serialized_end=147
FizzyOcrPaddle = service_reflection.GeneratedServiceType('FizzyOcrPaddle', (_service.Service,), dict(
  DESCRIPTOR = _FIZZYOCRPADDLE,
  __module__ = 'fizzy_ocr_paddle_pb2'
  ))

FizzyOcrPaddle_Stub = service_reflection.GeneratedServiceStubType('FizzyOcrPaddle_Stub', (FizzyOcrPaddle,), dict(
  DESCRIPTOR = _FIZZYOCRPADDLE,
  __module__ = 'fizzy_ocr_paddle_pb2'
  ))


# @@protoc_insertion_point(module_scope)
