# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fizzy_ocr_paddle.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import service as _service
from google.protobuf import service_reflection
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import annotations_pb2 as annotations__pb2
import fizzy_ocr_pb2 as fizzy__ocr__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x66izzy_ocr_paddle.proto\x12\x0e\x66izzyocrpaddle\x1a\x11\x61nnotations.proto\x1a\x0f\x66izzy_ocr.proto2j\n\x08\x46izzyOcr\x12^\n\x11GeneralPrintOCRV1\x12\x0e.GeneralOCRReq\x1a\x13.GeneralPrintOCRRsp\"$\x82\xd3\xe4\x93\x02\x1e\"\x19/ocr-api/print/general/v1:\x01*B\x03\x90\x01\x01\x62\x06proto3')



_FIZZYOCR = DESCRIPTOR.services_by_name['FizzyOcr']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\220\001\001'
  _FIZZYOCR.methods_by_name['GeneralPrintOCRV1']._options = None
  _FIZZYOCR.methods_by_name['GeneralPrintOCRV1']._serialized_options = b'\202\323\344\223\002\036\"\031/ocr-api/print/general/v1:\001*'
  _FIZZYOCR._serialized_start=78
  _FIZZYOCR._serialized_end=184
FizzyOcr = service_reflection.GeneratedServiceType('FizzyOcr', (_service.Service,), dict(
  DESCRIPTOR = _FIZZYOCR,
  __module__ = 'fizzy_ocr_paddle_pb2'
  ))

FizzyOcr_Stub = service_reflection.GeneratedServiceStubType('FizzyOcr_Stub', (FizzyOcr,), dict(
  DESCRIPTOR = _FIZZYOCR,
  __module__ = 'fizzy_ocr_paddle_pb2'
  ))


# @@protoc_insertion_point(module_scope)
